export enum ROLE {
  USER = 'USER',
  PLAYER = 'PLAYER',
  CAPTAIN = 'CAPTAIN',
  COACH = 'COACH',
  MANAGER = 'MANAGER',
  OWNER = 'OWNER',
  ORG_OWNER = 'ORGOWNER',
  MODERATOR = 'MODERATOR',
  LEAGUESTAFF = 'LEAGUESTAFF',
  HEADSTAFF = 'HEADSTAFF',
  ADMIN = 'ADMIN',
  LEAGUEADMIN = 'LEAGUEADMIN',
  SUPERADMIN = 'SUPERADMIN',
}

export const staffPortalPermissions = [
  ROLE.SUPERADMIN,
  ROLE.LEAGUEADMIN,
  ROLE.ADMIN,
  ROLE.HEADSTAFF,
  ROLE.LEAGUESTAFF,
]